Loaded 1 valid graphs.
Bug file id: 8d22b215
Performing initial feedback checks...
/home/iany/.local/lib/python3.10/site-packages/coverage/inorout.py:519: CoverageWarning: Module networkx was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")
4, 0.28092122077941895
Initial feedback check passed for graph 1.
33, 1.0625708103179932
21, 1.814382553100586
/home/iany/.local/lib/python3.10/site-packages/coverage/inorout.py:519: CoverageWarning: Module networkx was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")
50, 5.606986999511719
2, 6.376245975494385
2, 16.256367683410645
Ctrl+C pressed, finalizing...
Finalizing process...
count 8350
There were 6 graphs saved in the corpus.
Time spent: 119.997 minutes.
Exception: {0: "'int' object has no attribute 'is_directed'", <networkx.classes.graph.Graph object at 0x7fda86348400>: 'Disconnected graph: Ambiguous solution for bipartite sets.', <networkx.classes.graph.Graph object at 0x7fda863492a0>: 'Graph is not bipartite.', <networkx.classes.graph.Graph object at 0x7fda841a1840>: "('Connectivity is undefined ', 'for the null graph.')"}
Exception graphs saved to /home/iany/GraphFuzz/Log/max_matching_corpus_exceptions.pkl
Total Bugs Found:
Checking completed.
