Loaded 1 valid graphs.
Bug file id: 258ca914
Performing initial feedback checks...
/home/iany/.local/lib/python3.10/site-packages/coverage/inorout.py:519: CoverageWarning: Module networkx was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")
4, 0.15616989135742188
Initial feedback check passed for graph 1.
/home/iany/.local/lib/python3.10/site-packages/coverage/inorout.py:519: CoverageWarning: Module networkx was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")
101, 1.1145586967468262
2, 1.867365837097168
1, 2.615281581878662
2, 18.47991681098938
2, 26.128514766693115
Ctrl+C pressed, finalizing...
Finalizing process...
count 8350
There were 6 graphs saved in the corpus.
Time spent: 119.997 minutes.
Exception: {0: "'int' object has no attribute 'is_directed'", <networkx.classes.graph.Graph object at 0x7fda86797df0>: 'Disconnected graph: Ambiguous solution for bipartite sets.', <networkx.classes.graph.Graph object at 0x7fda84220f10>: 'Graph is not bipartite.', <networkx.classes.graph.Graph object at 0x7fda84198eb0>: "('Connectivity is undefined ', 'for the null graph.')"}
Exception graphs saved to /home/iany/GraphFuzz/Log/max_matching_corpus_exceptions.pkl
Total Bugs Found:
Checking completed.
