Loaded 1 valid graphs.
Bug file id: 36e2ab8f
Performing initial feedback checks...
/home/iany/.local/lib/python3.10/site-packages/coverage/inorout.py:519: CoverageWarning: Module networkx was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")
4, 0.34026598930358887
Initial feedback check passed for graph 1.
/home/iany/.local/lib/python3.10/site-packages/coverage/inorout.py:519: CoverageWarning: Module networkx was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")
101, 0.8382430076599121
2, 1.2261607646942139
2, 2.441679000854492
2, 3.6486072540283203
1, 4.8404552936553955
Ctrl+C pressed, finalizing...
Finalizing process...
count 13840
There were 6 graphs saved in the corpus.
Time spent: 120.002 minutes.
Exception: {0: "'int' object has no attribute 'is_directed'", <networkx.classes.graph.Graph object at 0x7f7237a72680>: 'Disconnected graph: Ambiguous solution for bipartite sets.', <networkx.classes.graph.Graph object at 0x7f7274a78f40>: "('Connectivity is undefined ', 'for the null graph.')", <networkx.classes.graph.Graph object at 0x7f7274a79fc0>: 'Graph is not bipartite.'}
Exception graphs saved to /home/iany/GraphFuzz/Log/max_matching_corpus_exceptions.pkl
Total Bugs Found:
Checking completed.
