Loaded 1 valid graphs.
Bug file id: 8db9262e
Performing initial feedback checks...
Initial feedback check passed for graph 1.
/home/iany/.local/lib/python3.10/site-packages/coverage/inorout.py:519: CoverageWarning: Module networkx was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")
70, 0.964299201965332
1, 3.773829221725464
1, 45.9964497089386
Ctrl+C pressed, finalizing...
Finalizing process...
count 7759
There were 312 graphs saved in the corpus.
Time spent: 119.997 minutes.
Exception: {<networkx.classes.graph.Graph object at 0x7f1aa68fbf40>: "Error: ('Contradictory paths found:', 'negative weights?')", <networkx.classes.graph.Graph object at 0x7f1aa68fbdf0>: "('Contradictory paths found:', 'negative weights?')"}
Exception graphs saved to /home/iany/GraphFuzz_v2/Log/hc_corpus_exceptions.pkl
Total Bugs Found:
Checking completed.
