Loaded 1 valid graphs.
Bug file id: 973cdc95
Performing initial feedback checks...
Initial feedback check passed for graph 1.
/home/iany/.local/lib/python3.10/site-packages/coverage/inorout.py:519: CoverageWarning: Module networkx was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")
68, 0.5338950157165527
2, 2.6719107627868652
1, 4.7008161544799805
1, 36.95941185951233
Ctrl+C pressed, finalizing...
Finalizing process...
count 7843
There were 310 graphs saved in the corpus.
Time spent: 119.997 minutes.
Exception: {<networkx.classes.graph.Graph object at 0x7f1aa6aa1720>: "Error: ('Contradictory paths found:', 'negative weights?')", <networkx.classes.graph.Graph object at 0x7f1aa6ebf880>: "('Contradictory paths found:', 'negative weights?')"}
Exception graphs saved to /home/iany/GraphFuzz_v2/Log/hc_corpus_exceptions.pkl
Total Bugs Found:
Checking completed.
